nginx:
    build: ./nginx
    links:
        - django:django
    ports:
        - "80:80"

postgres:
    image: postgres

django:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    links:
        - postgres:postgres
